import { Project } from "../../types";

// VSCode will generate this
const fakeProject: { [K in keyof Required<Project>]: K } = {
  slug: "slug",
  "": "",
  original_source_name: "original_source_name",
  original_source_organization: "original_source_organization",
  verification_status: "verification_status",
  verified_by: "verified_by",
  verified_on: "verified_on",
  comment: "comment",
  ref: "ref",
  project_name: "project_name",
  active: "active",
  website: "website",
  categories: "categories",
  main_category: "main_category",
  sub_categories: "sub_categories",
  sub_categories_1: "sub_categories_1",
  sub_categories_2: "sub_categories_2",
  sub_categories_3: "sub_categories_3",
  sub_categories_4: "sub_categories_4",
  first_sdg: "first_sdg",
  second_sdg: "second_sdg",
  third_sdg: "third_sdg",
  fourth_sdg: "fourth_sdg",
  sdg_occurences: "sdg_occurences",
  number_of_sd_gs: "number_of_sd_gs",
  description_short_value_proposition_in_a_tweet:
    "description_short_value_proposition_in_a_tweet",
  long_description: "long_description",
  tags_keywords: "tags_keywords",
  business_tagline: "business_tagline",
  primary_headquarter_city: "primary_headquarter_city",
  primary_headquarter_country: "primary_headquarter_country",
  secondary_headquarter_city: "secondary_headquarter_city",
  secondary_headquarter_country: "secondary_headquarter_country",
  hq_region: "hq_region",
  hq_subregion: "hq_subregion",
  year_creation: "year_creation",
  founder_names: "founder_names",
  organization_type: "organization_type",
  twitter_url: "twitter_url",
  facebook_url: "facebook_url",
  linkedin_url: "linkedin_url",
  discord_url: "discord_url",
  video_url: "video_url",
  white_paper_url: "white_paper_url",
  coin_market_cap_url: "coin_market_cap_url",
  github_url: "github_url",
  other_links: "other_links",
  logo_url: "logo_url",
  token_ticker: "token_ticker",
  blockchain_type: "blockchain_type",
  blockchain_technology: "blockchain_technology",
  coinmarketcap_url: "coinmarketcap_url",
  github_link: "github_link",
  sponsors_partners: "sponsors_partners",
  servicing_area: "servicing_area",
  servicing_region: "servicing_region",
  subregions: "subregions",
  global_north_south: "global_north_south",
  pb_personal_contact: "pb_personal_contact",
  project_official_email: "project_official_email",
  individual_contact_1_at_project: "individual_contact_1_at_project",
  email_1: "email_1",
  individual_contact_2_at_project: "individual_contact_2_at_project",
  email_2: "email_2",
  partner_tag: "partner_tag",
};

export const projectProperties = Object.keys(fakeProject).reduce((acc, key) => {
  acc[key] = { type: "string" };
  return acc;
}, {} as Record<string, { type: string }>);
