import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function RetoolExample() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <iframe
        style={{
          height: "100vh",
          border: 0,
        }}
        src="https://positiveblockchain.retool.com/apps/Projects%20Dashboard"
        // src="https://positiveblockchain.retool.com/embedded/public/857dd8a6-4e15-4b6d-b5be-2fb65803ab72"
        width="100%"
      ></iframe>
    </>
  );
}
