export type Project = {
  slug: string;
  "": string;
  original_source_name: string;
  original_source_organization: string;
  verification_status: string;
  verified_by: string;
  verified_on: string;
  comment: string;
  ref: string;
  project_name: string;
  active: string;
  website: string;
  categories: string;
  main_category: string;
  sub_categories: string[];
  sub_categories_1: string;
  sub_categories_2: string;
  sub_categories_3: string;
  sub_categories_4: string;
  first_sdg: string;
  second_sdg: string;
  third_sdg: string;
  fourth_sdg: string;
  sdg_occurences: string;
  number_of_sd_gs: string;
  description_short_value_proposition_in_a_tweet: string;
  long_description: string;
  tags_keywords: string;
  business_tagline: string;
  primary_headquarter_city: string;
  primary_headquarter_country: string;
  secondary_headquarter_city: string;
  secondary_headquarter_country: string;
  hq_region: string;
  hq_subregion: string;
  year_creation?: string;
  founder_names?: string;
  organization_type?: string;
  twitter_url?: string;
  facebook_url?: string;
  linkedin_url?: string;
  discord_url?: string;
  video_url?: string;
  white_paper_url?: string;
  coin_market_cap_url?: string;
  github_url?: string;
  other_links?: string;
  logo_url?: string;
  token_ticker?: string;
  blockchain_type?: string;
  blockchain_technology?: string;
  coinmarketcap_url?: string;
  github_link?: string;
  sponsors_partners?: string;
  servicing_area?: string;
  servicing_region?: string;
  subregions?: string;
  global_north_south?: string;
  pb_personal_contact?: string;
  project_official_email?: string;
  individual_contact_1_at_project?: string;
  email_1?: string;
  individual_contact_2_at_project?: string;
  email_2?: string;
  partner_tag?: string;
};

export type ProjectDataSchema = {
  [data_key: string]: {
    headerTitle: string;
    columnIdx: number;
    type: "text" | "list" | "boolean";
  };
};

export interface CountryData {
  country: string;
  subregion: string;
  region: string;
  hemisphere: string;
}
