export const SAMPLE_DATA = [
  [
    "Instructions:\n" +
      "- Row 2 is the keys that are used for finding/organizing data. If you update those, it will have an effect on the entire system.\n" +
      "- All columns are private by default.\n" +
      '- You must prefix a key with "PUBLIC_" to expose it to the public ',
  ],
  [
    "submitted_at",
    "original_source_name",
    "original_source_organization",
    "",
    "verification_status",
    "verified_by",
    "verified_on",
    "comment",
    "ref",
    "PUBLIC_project_name",
    "PUBLIC_active",
    "PUBLIC_website",
    "PUBLIC_categories_list",
    "PUBLIC_main_category",
    "PUBLIC_sub_categories_list",
    "sub_categories_1",
    "sub_categories_2",
    "sub_categories_3",
    "sub_categories_4",
    "first_sdg",
    "second_sdg",
    "third_sdg",
    "fourth_sdg",
    "PUBLIC_sdg_occurrences_list",
    "number_of_sd_gs_list",
    "PUBLIC_description_short_value_proposition_in_a_tweet",
    "PUBLIC_long_description",
    "PUBLIC_tags_keywords_list",
    "PUBLIC_business_tagline",
    "PUBLIC_primary_headquarter_city",
    "PUBLIC_primary_headquarter_country",
    "PUBLIC_secondary_headquarter_city",
    "PUBLIC_secondary_headquarter_country",
    "PUBLIC_hq_region",
    "PUBLIC_hq_subregion",
    "PUBLIC_year_creation",
    "PUBLIC_founder_names_list",
    "PUBLIC_organization_type",
    "PUBLIC_twitter_url",
    "PUBLIC_facebook_url",
    "PUBLIC_linkedin_url",
    "PUBLIC_discord_url",
    "PUBLIC_video_url",
    "PUBLIC_white_paper_url",
    "PUBLIC_coin_market_cap_url",
    "PUBLIC_github_url",
    "PUBLIC_other_links_list",
    "PUBLIC_logo_url",
    "PUBLIC_token_ticker",
    "PUBLIC_blockchain_type",
    "PUBLIC_blockchain_technology",
    "PUBLIC_coinmarketcap_url",
    "PUBLIC_github_link",
    "PUBLIC_sponsors_partners_list",
    "PUBLIC_servicing_area",
    "PUBLIC_servicing_region",
    "PUBLIC_subregions_list",
    "",
    "PUBLIC_pb_partner_tag",
  ],
  [
    "Cell instructions",
    "important for us to know who identified new projects. allows to reward contribution. if you add a new, Add your name",
    "if you add a new, add the name of your organization",
    "",
    "new item. would help flag newly imported project / to be verified). Options verified / unverified",
    "new item",
    "new item",
    "",
    "just to keep track of the order of adding new projects. if you add one, please add down the table and put a reference #",
    "Name (respect official name: capital letters, spacing, etc..)",
    "Active, Inactive, Active - no blockchain any longer",
    "website URL",
    'All main categories separated by comma. To use Multiple-Select, go to the menu on top, and click "Multiple Select".',
    'choose main category to link the project with. To use Multiple-Select, go to the menu on top, and click "Multiple Select".',
    'Check tab Category. You should only elect the tags below the selected catagories. several tags possible,in that case separate with ",". To use Multiple-Select, go to the menu on top, and click "Multiple Select".',
    "manual step: copy paste text from previous column to columns",
    "",
    "",
    "",
    "NE PAS TOUCHER / Formules",
    "NE PAS TOUCHER / Formules",
    "NE PAS TOUCHER / Formules",
    "NE PAS TOUCHER / Formules",
    'here the formula should give "," before and after each number for easier treatment with formulas',
    "counts the number of commas -1",
    'Short description needs to stay short but specific enough, comprehensive and start with "a" or "the". (should have a limit of number of character)',
    "Long description with details. This will go to single project pages. No character restriction",
    "List of tags, keywords, related to the project and separated by comma ",
    "Tagline or motto can usually be found on the website, on twitter, or directly on google when typing the name. 110 characters max",
    ' "City", "Country"',
    ' "City", "Country". "Distributed" if this is the case. To use Multiple-Select, go to the menu on top, and click "Multiple Select".',
    "",
    "",
    "",
    "",
    'year only. can be found easily on twitter or linkedin description pages, or techcrunch database. To use Multiple-Select, go to the menu on top, and click "Multiple Select".',
    'Founders only. Please respect this formatting -> "Name", "Tittle"; "Name", Tittle"',
    'select right data or mulptiple by separating with ",". data field in the tab "DB Instructions". To use Multiple-Select, go to the menu on top, and click "Multiple Select".',
    "Twitter URL (not the handle alone)",
    "Facebook URL",
    "Linkedin URL",
    "",
    "Youtube or Vimeo URL (main video, only one)",
    "URL of white paper",
    "If a public blockchain, link to http://coinmarketcap.com/  if available",
    "If public/open source link to https://github.com/ here",
    "Paste here other related articles talking about the project, if relevant. several articles possible",
    "",
    "only capital letters",
    "Write here: Public, Private, Not known",
    "",
    "",
    "",
    "",
    'Region means the regions of activity. Some project focus on specific cities or countries, some just have a global coverage.  So you can write "City" or  "Country" or "Continent". Could have several ones, then separate by ";". If global, then specify "Global"',
    "",
    "",
    "",
    "",
    "if we have personal contacts mention it here with your name",
  ],
  [
    "Comments for Andrew",
    "internal data",
    "internal data",
    "",
    "internal data",
    "internal data",
    "internal data",
    "internal data",
    "internal data. helps to reconciliate projects",
    "Mandatory",
    "Mandatory",
    "the unique identifier",
    "Mandatory",
    "Mandatory",
    "Mandatory",
    "internal, just used to split sub-categories and derive SDGs using the SDG data table",
    "internal, just used to split sub-categories and derive SDGs using the SDG data table",
    "internal, just used to split sub-categories and derive SDGs using the SDG data table",
    "internal, just used to split sub-categories and derive SDGs using the SDG data table",
    "internal, just used to derive SDGs using the SDG data table",
    "internal, just used to derive SDGs using the SDG data table",
    "internal, just used to derive SDGs using the SDG data table",
    "internal, just used to derive SDGs using the SDG data table",
    "internal, just used to derive SDGs using the SDG data table",
    "internal, just used to derive SDGs using the SDG data table",
    "Mandatory",
    "",
    "",
    "The front-end page would ideal integrate this (short sentence below title), but it is not mandatory. so the UI could integrate both text or empty value",
    "the website will show only the primary one on front-end pages",
    "the website will show only the primary one on front-end pages",
    "",
    "",
    "",
    "",
    "",
    'we need to check this one. For the moment it should be ok if we just display it as text string. the formatting until now was: "Founder name, position; founder name, position"... so we need to detect it or transform into another format',
    "",
    "ideally we could have the front-end pages showing logos",
    "ideally we could have the front-end pages showing logos",
    "ideally we could have the front-end pages showing logos",
    "ideally we could have the front-end pages showing logos",
    "could be integrated in the front-end is it exists.. ",
    "",
    "",
    "",
    "",
    "need to discuss if this is relevant or will be done another way. if we upload logo on media or wordpress, we could have the logo URL here then?",
    "this could allow for integration with onchain market data in the future like coinmarketcap data",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "for internal use",
    "for internal use",
    "for internal use",
    "for internal use",
    "for internal use",
    "for internal use",
    'for internal use. this one could help us identify a specific partner like "UN", "ECOTA" to facilitate filtering/ export operations',
    "could be interesting to understand how to automate this in the future. Would help suggest a related age to the user after visiter a page from the front interface",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
    "these are out of scope, we seek to remove them",
  ],
  [
    "",
    "100%",
    "100%",
    "",
    "",
    "",
    "",
    "",
    "100%",
    "1206",
    "100%",
    "99%",
    "100%",
    "100%",
    "100%",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "94%",
    "55%",
    "0%",
    "39%",
    "74%",
    "85%",
    "2%",
    "2%",
    "",
    "",
    "81%",
    "40%",
    "84%",
    "45%",
    "29%",
    "34%",
    "",
    "24%",
    "23%",
    "0%",
    "0%",
    "22%",
    "",
    "22%",
    "49%",
    "59%",
    "",
    "",
    "14%",
    "36%",
    "",
    "",
    "",
    "",
    "6%",
    "55%",
    "1%",
    "18%",
    "16%",
    "",
    "4%",
  ],
  [
    "",
    "Original source name",
    "Original source organization",
    "Last project submit",
    "Verification status",
    "verified by",
    "verified on",
    "Comment",
    "REF #",
    "Project name",
    "Active",
    "Website",
    "Categories",
    "Main Category",
    "Sub-Categories",
    "SUB-CATEGORIES 1",
    "SUB-CATEGORIES 2",
    "SUB-CATEGORIES 3",
    "SUB-CATEGORIES 4",
    "first SDG",
    "second SDG",
    "third SDG",
    "fourth SDG",
    "SDG occurences",
    "number of SDGs",
    "DESCRIPTION SHORT = VALUE PROPOSITION IN A TWEET",
    "LONG DESCRIPTION",
    "Tags & keywords",
    "BUSINESS TAGLINE",
    "Primary Headquarter city",
    "Primary Headquarter country",
    "Secondary Headquarter city",
    "Secondary Headquarter country",
    "HQ region",
    "HQ subregion",
    "Year Creation",
    "Founder Names",
    "Organization type",
    "Twitter URL",
    "Facebook URL",
    "Linkedin URL",
    "Discord URL",
    "Video URL",
    "White Paper URL",
    "CoinMarketCap URL",
    "Github URL",
    "Other links",
    "Logo URL",
    "Token ticker",
    "Blockchain type",
    "Blockchain technology",
    "Coinmarketcap URL",
    "Github link",
    "Sponsors & partners",
    "Servicing area",
    "Servicing region",
    "Subregions",
    "Global North/South",
    "PB partner tag",
    "PB PERSONAL CONTACT",
    "PROJECT OFFICIAL EMAIL",
    "Individual contact 1 at project",
    "Email 1",
    "Individual contact 2 at project",
    "Email 2",
    "Partner Tag",
    "Related page",
    "PRIVATE__USE OF BLOCKCHAIN",
    "PRIVATE__NUMBER OF USERS",
    "PRIVATE__NUMBER OF FTE STAFF",
    "PRIVATE__BENEFICIARIES IMPACTED",
    "PRIVATE__FUNDRAISING TYPE",
    "PRIVATE__FUNDRAISING/ICO START DATE",
    "PRIVATE__TARGET GROUP",
    "PRIVATE__Servicing in Africa?",
    "PRIVATE__FEMALE FOUNDER",
    "PRIVATE__(AGRI-FOOD DATASET) type of products",
    "PRIVATE__(AGRI-FOOD DATASET) activity",
    "PRIVATE__IMPACT FIRST?",
  ],
  [
    "",
    "pb website form",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.424",
    "1141",
    "Token Engineering Commons (TEC)",
    "Active",
    "https://tecommons.org/",
    "Government & Democracy,Finance & Insurance",
    "Finance & insurance",
    "Financial Inclusion,Community Mobilization,",
    "Financial Inclusion",
    "Community Mobilization",
    "",
    "",
    "1, 17",
    "11, 16",
    "",
    "",
    ",1,17,11,16,",
    "4",
    "an initiative all about designing, modeling, and simulating tokenized ecosystems. The Token Engineering Commons seeks to be the mecca for this nascent discipline, funding and supporting projects that want to develop research, education materials, open source software, and initiatives that want to grow our collective understanding and proper usage of crypto-economic systems.",
    "Within our partners’ goal of funding digital public goods, the scope of TEC’s mission is specific to funding token engineering-related digital public goods. For example, we’ve created a Commons Configuration Dashboard (https://config.tecommons.org), which is open source and free to use, where users can input different values for the parameters that support a collaborative economy (i.e. a DAO). Then, the dashboard calculates how one variable affects the other variables and displays a graph that allows one to visualize the different interrelationships between input and behaviour.",
    "",
    "",
    "",
    "Distributed",
    "",
    "",
    "#N/A",
    "#N/A",
    "2020",
    "",
    "DAO",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/watch?v=vf1rOMDzw38",
    "",
    "",
    "",
    "",
    "",
    "TEC",
    "Public",
    "Gardens, xDAI",
    "",
    "https://github.com/CommonsBuild/tec-info",
    "",
    "Global",
    "Global",
    "Global",
  ],
  [
    "",
    "pb website form",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.424",
    "1146",
    "Porini.Foundation",
    "Active",
    "https://porini.foundation/",
    "Climate & Environment",
    "Climate & Environment",
    "Biodiversity,Climate & carbon reduction",
    "Biodiversity",
    "Climate & carbon reduction",
    "",
    "",
    "14, 15",
    "13",
    "",
    "",
    ",14,15,13,",
    "3",
    'a charities offering Nature Collectibles, CO2 from Nature-based Solutions, a zero-carbon sustainability chain based upon "proof of authority".',
    "Our Nature Collectibles is creating a digital collection of endangered species, to finance conservation sites in partnership with IUCN.",
    "",
    "",
    "Fribourg",
    "Switzerland",
    "",
    "",
    "Europe",
    "Central Europe",
    "2018",
    "",
    "foundation",
    "",
    "",
    "https://www.linkedin.com/company/porini-foundation/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "IMD",
    "Not Known",
    "xDAI",
    "",
    "https://github.com/SustainabilityChain/NatureCollectibles",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "ECOTA",
  ],
  [
    "",
    "PB contributor (add or edit): : Azusa",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.513",
    "177",
    "TraSeable Solutions",
    "Active",
    "https://traseable.com",
    "Agriculture & Food,Logistics & Traceability,Climate & Environment,",
    "Agriculture & Food",
    "Supply Chain Transparency,Food Transparency,Life below Water",
    "Supply Chain Transparency",
    "Food Transparency",
    "Biodiversity",
    "",
    "45,268",
    "2, 15",
    "14, 15",
    "",
    ",8,12,2,15,14,15,",
    "6",
    "the seafood supply chain, providing the full transparency and traceability required to enable the market to reward responsible and ethical producers, and push those that are illegal and unethical out of the supply chain.",
    "TraSeable Solutions supports global seafood sustainability through a blockchain-ready software-as-a-service (SaaS) platform for seafood traceability that fosters collaboration between stakeholders, leverages and integrates Internet of Things (IoT) technology.                                                                                                                                                       To promote transparency and traceability by providing an adaptable, affordable, secure, and collaborative platform that allows for efficient information sharing between all supply chain stakeholders.                                                                                                                                                                                           To help alleviate Illegal, Unregulated and Unreported (IUU) fishing within the Pacific and support responsible fishing practices.\n" +
      "To connect consumers to product provenance and authenticity through product story.           ",
    "",
    "",
    "",
    "Fiji",
    "",
    "",
    "Oceania",
    "Oceania",
    "2017",
    "Kenneth Katafono, FOUNDER & MANAGING DIRECTOR",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/traseablefiji/about/",
    "",
    "",
    "",
    "",
    "",
    "https://viant.io/",
    "",
    "",
    "Private",
    "Ethereum, Treum",
    "",
    "",
    "Viant,Consensys,WWF NZ",
    "Fiji",
    "",
    "",
    "",
    "",
    "",
    "info@traseable.com",
    "",
    "Kenneth Katafono",
    "Kenneth@traseable.com",
    "Shauna Tagaloa Katafono",
  ],
  [
    "",
    "Ronald",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.367",
    "987",
    "SmartCredit",
    "Active",
    "https://smartcredit.io/",
    "Finance & Insurance",
    "Finance & Insurance",
    "Lending",
    "Lending",
    "Credit Scoring",
    "",
    "",
    "1, 17",
    "",
    "",
    "",
    ",1,17,",
    "2",
    "a decentralized system of crypto-credit money in the world, empowering people to take back control over their own money – without the commercial banks and fees",
    "",
    "",
    "",
    "Zug",
    "Switzerland",
    "",
    "",
    "Europe",
    "Central Europe",
    "2020",
    "",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/smartcredit-io/about/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, SmartCredit",
    "https://coinmarketcap.com/fr/currencies/smartcredit-token/",
  ],
  [
    "",
    "unknown (probably: PB research)",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.5",
    "156",
    "Devery",
    "Active",
    "https://devery.io/",
    "Logistics & Traceability",
    "Logistics & Traceability",
    "Supply Chain Transparency",
    "Supply Chain Transparency",
    "",
    "",
    "",
    "45,268",
    "",
    "",
    "",
    ",8,12,",
    "2",
    "a blockchain powered, open-source, product verification protocol",
    "Devery is focused on providing verification services on the Ethereum network. It is an open-source, blockchain powered verification system aiming to unify seperate verification platforms on the Ethereum blockchain.\n",
    "",
    "",
    "Sydney",
    "Australia",
    "",
    "",
    "Oceania",
    "Oceania",
    "2017",
    "Andrew Rasheed, Founder & CEO",
    "start-up",
    "",
    "",
    "",
    "",
    "",
    "https://devery.io/whitepaper/Devery_Whitepaper_rev5.pdf",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Smart Contract (EVE)",
    "https://coinmarketcap.com/fr/currencies/devery/",
    "https://github.com/devery",
    "",
    "Tunisia, New York, Malaysia, Singapore,Mexico, Beijing",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Andrew Rasheed",
    "Andrew@devery.io",
    "Chironjit Das",
  ],
  [
    "",
    "JAFS",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.412",
    "1093",
    "Compound Labs",
    "Active",
    "http://compound.finance/",
    "Finance & Insurance",
    "Finance & Insurance",
    "Lending,Credit Scoring",
    "Lending",
    "",
    "",
    "",
    "1, 17",
    "1, 17",
    "",
    "",
    ",1,17,1,17,",
    "4",
    "an open-source software development company building tools, products, and services for the decentralized finance (DeFi) ecosystem.",
    "Compound is an algorithmic, autonomous interest rate protocol built for developers, to unlock a universe of open financial applications.\n",
    "",
    "",
    "San Francisco",
    "United States",
    "",
    "",
    "North America",
    "North America",
    "2017",
    "",
    "Open source",
    "https://twitter.com/compoundfinance",
    "",
    "https://www.linkedin.com/company/compound-labs/about/",
    "",
    "",
    "",
    "",
    "",
    "https://compound.finance/docs",
    "",
    "COMP",
    "Public",
    "Ethereum, Smart contract",
    "https://coinmarketcap.com/currencies/compound/",
  ],
  [
    "",
    "unknown (probably: PB research)",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.388",
    "808",
    "Digiland",
    "Active",
    "https://www.digilandgroup.com/",
    "Identity & Ownership",
    "Identity & Ownership",
    "Land & Titling",
    "Land & Titling",
    "",
    "",
    "",
    "9",
    "",
    "",
    "",
    ",9,",
    "1",
    "an impact driven e-governance company based in Bangladesh. We digitize land titles and develop a blockchain based app to provide a transparent, secure and convenient way to prove land title authenticity",
    "",
    "",
    "Securing land titles with Blockchain technology\n",
    "Dhaka",
    "Bengladesh",
    "",
    "",
    "Asia",
    "Southern Asia",
    "2018",
    "Sanjana Sadique, Moin Ghani, Niklas Friese",
    "Government Partnership",
    "",
    "",
    "https://www.linkedin.com/company/digilandgroup/about/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Sidechain",
  ],
  [
    "",
    "PB contributor (add or edit): : Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.463",
    "626",
    "Modum",
    "Active",
    "https://modum.io",
    "Health,Logistics & Traceability",
    "Health",
    "Patient Data",
    "Patient Data",
    "",
    "",
    "",
    "3",
    "",
    "",
    "",
    ",3,",
    "1",
    "a system for supply chain data, become most valuable intelligence, automating business processes and bridging with external data silos",
    "Data integrity for supply chain operations, powered by cutting-edge blockchain & IoT technology.\n" +
      " \n" +
      " Modum offers a digital supply chain monitoring & optimization solution that measures environmental conditions at high shipment volumes for the pharma industry. Our first solution enables pharma distributors to fulfil regulatory obligations under GDP in an efficient and cost effective way.\n" +
      " \n" +
      " Modum is currently in collaboration with Swiss Post and SAP. Our first solution allows for user-friendly deviation management in a web application. It offers instant notifications of temperature excursions and other events, such as motion, when the sensing device is read out wirelessly. The entire solution can be seamlessly integrated with existing workflows and enterprise management systems, such as SAP, and leverage a recorded trusted event for further process automation. It also integrates well with track-and-trace systems across supply chains, allowing automatic and reliable notifications at the time of shipment hand-over.",
    "",
    "",
    "Zurich",
    "Switzerland",
    "",
    "",
    "Europe",
    "Central Europe",
    "2016",
    "Simon Dössegger, CEO; Dr. Stefan M. Weber, COO; Sacha Uhlmann, CTO",
    "start-up",
    "https://twitter.com/modum_io?lang=en",
    "",
    "",
    "",
    "https://www.youtube.com/watch?v=cEItzlSz1xw",
    "https://modum.io/sites/default/files/documents/2018-05/modum-whitepaper-v.-1.0.pdf",
    "",
    "",
    "",
    "",
    "MOD",
    "Private",
    "Hyperledger, SAP Blockchain Service",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "info@websummit.net",
    "",
    "Robert",
  ],
  [
    "",
    "unknown (probably: PB research)",
    "Positiveblockchain",
    "",
    "",
    "",
    "last quality check Karsten: 06.02.19",
    "0.545",
    "56",
    "Nori",
    "Active",
    "https://nori.com",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & Carbon reduction",
    "Climate & Carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "a company on a mission to Reverse Climate Change, by creating the world's first ever marketplace for CO2 removal, backed by a blockchain",
    "We need carbon removal to balance out atmospheric CO2 levels and ultimately help reverse climate change.\n" +
      "\n" +
      "The clock is ticking.\n" +
      "Currently, atmospheric CO2 levels are at ~405–410 parts per million (ppm). Levels above 450 ppm risk runaway feedback loops—including more warming—that will be difficult to stop.\n" +
      "\n" +
      "We can do this.\n" +
      "CO2 can be removed from the atmosphere by ecological and/or industrial means. It can be sequestered in trees, kelp, soil, minerals, and even manufactured products like plastics and timber.\n" +
      "\n" +
      "A new price on carbon.\n" +
      "Our new currency is backed by carbon removal. Every token is worth 1 ton of CO2 removal and will finance a new economy of restoration.\n" +
      "\n" +
      "Frequently Asked Questions\n" +
      "What are the different types of carbon removal?\n" +
      "There are many ways to remove carbon dioxide from the atmosphere. They fall into three main categories: ecological, industrial, and hybrid. \n" +
      "\n" +
      "Ecological carbon removal can be achieved through better management and restoration of ecosystems on land and in the ocean.\n" +
      "\n" +
      "Reforestation is the establishment of forests or stands of trees where there previously was no recent forest cover. Carbon dioxide is captured by photosynthesis and is stored in the biomass of the forest. \n" +
      "Blue Carbon refers to carbon captured by the world’s oceans and coastal ecosystems. The carbon is captured by marine life, and ends up being stored as biomass or in sediments. Algae, kelp, mangroves, salt marshes, and seagrasses can all sequester carbon. Many animals help drive these processes, including sea otters, tiger sharks, turtles, and sperm whales.\n" +
      "Soil Carbon Storage refers to techniques that can increase the organic and inorganic matter stored soils on farms and other managed lands. \n" +
      "Industrial carbon removal refers to engineered solutions that do not depend on ecological processes. \n" +
      "\n" +
      "Direct air capture with mineral geologic sequestration uses machines to extract and concentrate carbon dioxide to store in mineral carbonates with no economic value. \n" +
      "Direct air capture into products uses machines to extract and concentrate carbon dioxide into products ranging from concrete, polymers, graphene, and other stable materials containing carbon molecules formerly in the air. \n" +
      "Hybrid carbon removal solutions combine ecological and industrial processes. \n" +
      "\n" +
      "Bioenergy with Carbon Capture and Storage (BECCS) relies on biomass to remove carbon dioxide, generate energy at a power plant, and produce gaseous emissions which can be captured and stored underground. \n" +
      "Biochar also relies on biomass to remove carbon dioxide and generate energy, but has a process that starves the fuel of oxygen, thereby leaving behind a residue that when spread over soil creates a negative emission. \n" +
      "Biosequestration in materials is any approach that leverages biology to create a carbon sink in products—ranging from carpets to clothes to building materials. \n" +
      "Enhanced weathering covers a number of geologic processes that occur on land or in ocean where certain minerals react with carbon dioxide and turn it into a solid, sequestered form.\n" +
      " \n" +
      "What is Carbon Removal?\n" +
      "Carbon removal refers to any ecological or industrial approach that can take carbon dioxide out of atmospheric or oceanic circulation beyond what would have occurred without humans. Right now, carbon removal approaches have different costs, degrees of maturity, measurement needs, permanence, energy consumption/production, and additional uncertainties. But they are all the same in their growing potential as ways to capture and store carbon dioxide in order to help reverse climate change.\n" +
      "\n" +
      "Why do we need Carbon Removal to stop climate change?\n" +
      "Since the industrial revolution, mankind has burned fossil fuels to produce energy which release greenhouse gases. In spite of long understanding the clear linkage between excess greenhouse gases (predominantly carbon dioxide) in the atmosphere and oceans and global climate change, humans have been unable to stop emitting. While reducing and replacing carbon emissions are key components to slowing down the flow of greenhouse gases to the atmosphere, because carbon dioxide stays in the atmosphere for hundreds of years—warming the planet—the only way to stop the most severe effects of climate change is by balancing the total stock of carbon dioxide in the atmosphere. This can only be achieved through carbon removal.\n" +
      "\n" +
      "Why blockchain for carbon removal?\n" +
      "The blockchain allows for a number of new opportunities to establish a market for carbon removal. Blockchain technologies allow us to issue a token, NORI, which sets one uniform price on removing carbon dioxide. Because a carbon removal credit can only be used once, and is immediately retired, our blockchain system avoids double counting, which occurs in the design of all other traditional carbon offset schemes. Furthermore, using a blockchain solution allows for complete transparency to the new type of carbon removal asset. Blockchain allows for substantially lower verification costs through automation and removing the many middle men involved in traditional carbon removal transactions. Lastly, through using a blockchain token as a medium of exchange, this solution removes the requirement for project sellers and buyers to find a counterparty, allowing all parties to participate in a fungible market.\n" +
      "\n" +
      "How does the token relate to carbon removal?\n" +
      "1 Nori token allows for the purchase of a carbon removal credit (CRC). Think of it like a gift card that allows you to pay for carbon removal. One Nori token pays for one CRC. The Nori token can be purchased at any time and when it is spent in the Nori platform will immediately transfer ownership of a carbon removal credit to the buyer.\n" +
      "\n" +
      "Who can use the Nori platform?\n" +
      "While anyone can purchase a Carbon Removal credit with a Nori token, we’ve identified a few important categories to get started:\n" +
      "\n" +
      "Individuals who are looking for direct ways combat climate change\n" +
      "Cryptocurrency enthusiasts\n" +
      "Climate change activists\n" +
      "Businesses with a sustainability vision and carbon removal mandate\n" +
      "How do you generate carbon removal credits?\n" +
      "Whenever a seller performs a carbon removal action, we first verify that the carbon dioxide has actually been removed from the atmosphere and stored. The seller either uploads data manually, or the removal data is automatically reported into the Nori platform. This generates the creation of a new Carbon Removal Credit smart contract that is now available for purchase by a buyer.\n" +
      "\n" +
      "How is Nori different from other voluntary carbon offset registries?\n" +
      "We only accept carbon removal projects. Reductions in emissions are not good enough.\n" +
      "Nori abstracts the exchange of CRC for Nori tokens by selling CRCs to buyers in a First In First Out (FIFO) order as they’re entered into the marketplace. We are commoditizing CO2.\n" +
      "Nori reduces the overhead costs for CRC providers by as much as 50% through the use of automated sensors and Internet of Things devices to measure how much CO2 was removed.\n" +
      "By accounting for the ownership of the CRCs on the blockchain, Nori eliminates the double-counting problem that has plagued past attempts at creating healthy carbon offsets markets.\n" +
      "Nori is establishing the framework for carbon accounting methodologies that are transparent, iterative, and with an open-source software perspective. ",
    "",
    "On a mission to reverse climate change",
    "Seattle",
    "United States",
    "",
    "",
    "North America",
    "North America",
    "2017",
    "Paul Gambill",
    "start-up",
    "https://twitter.com/noridoteco",
    "https://www.facebook.com/noridoteco/",
    "",
    "",
    "https://www.youtube.com/watch?v=tFXx_XF9Eoo",
    "https://nori.com/white-paper",
    "",
    "",
    "https://medium.com/nori-carbon-removal/carbon-removal-blockchain-creates-a-new-way-to-reverse-climate-change-b2caa1a2bbcc",
    "",
    "NORI",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
    "",
    "hello@nori.com",
    "",
    "Paul Gambill",
    "Paul@nori.com",
    "Christophe Jospe",
    "x",
  ],
  [
    "",
    "added / claimed website",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.421",
    "913",
    "Treejer",
    "Active",
    "https://www.treejer.com",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & carbon reduction",
    "Climate & carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "a decentralized reforestation protocol connecting global tree funders to rural planters in less developed countries in a unique way that benefits all contributing individuals",
    "",
    "",
    "",
    "Tallinn",
    "Estonia",
    "",
    "",
    "Europe",
    "Northern Europe",
    "2018",
    "",
    "start-up,open-source",
    "",
    "",
    "https://www.linkedin.com/company/treejer/about/",
    "",
    "",
    "",
    "",
    "",
    "",
    "https://positiveblockchain.io/wp-content/uploads/2020/08/Treejer-Logo-n.png",
    "",
    "Public",
    "Ethereum, Polygon",
    "",
    "https://github.com/treejer/contract",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "pb website form",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.38",
    "1143",
    "CO2DAO",
    "Active",
    "https://www.co2dao.org/",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & carbon reduction",
    "Climate & carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "a project and token trying to create immediate value for climate action via blockchain technologies.",
    "",
    "",
    "",
    "Zug",
    "Switzerland",
    "",
    "",
    "Europe",
    "Central Europe",
    "2020",
    "",
    "DAO",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "Ronald",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.378",
    "940",
    "Doingud",
    "Active",
    "https://doingud.com/",
    "Aid & Philanthropy,Digital content & Arts",
    "Aid & Philanthropy",
    "Arts Music & Film,Donation & Charities",
    "Arts Music & Film",
    "Donation & Charities",
    "",
    "",
    "16",
    "10",
    "",
    "",
    ",16,10,",
    "2",
    "an NFT marketplace building the future of the creator and giving economy",
    "",
    "",
    "",
    "Zug",
    "Switzerland",
    "",
    "",
    "Europe",
    "Central Europe",
    "2021",
    "",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/doingudhq/about/",
    "",
    "",
    "",
    "",
    "",
    "https://linktr.ee/doingud",
    "",
    "",
    "Not known",
    "Ethereum, Polygon",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.507",
    "1117",
    "Eden DAO",
    "Active",
    "https://drm.edendao.finance/",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & carbon reduction",
    "Climate & carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "an OlympusDAO clone which aims to solve funding issues in the cabron credit markets, by leveraging crypto",
    "",
    "",
    "",
    "Distributed",
    "Distributed",
    "",
    "",
    "#N/A",
    "#N/A",
    "2021",
    "",
    "DAO",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.52",
    "1127",
    "BICOWG",
    "Active",
    "https://twitter.com/BICOWG",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & carbon reduction",
    "Climate & carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "a coalition of blockchain protocols, projects, and nonprofits working together to explore carbon measurement methodology and incentivize carbon markets. Core working group members include Regen Network, Klima DAO, Toucan, SZNS, FungyProof, F2Pool/Stakefish, Blockchain for Climate, and Gitcoin.",
    "",
    "",
    "",
    "Distributed",
    "Distributed",
    "",
    "",
    "#N/A",
    "#N/A",
    "2021",
    "",
    "partnership",
    "https://twitter.com/BICOWG",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.507",
    "1112",
    "Coorest",
    "Active",
    "https://coorest.eu/",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & carbon reduction",
    "Climate & carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "a decentralized carbon credit exchange from Netherlands, that uses NFTs and crypto-based yield-bearing assets to offer eco-friendly investment methods",
    "",
    "",
    "",
    "",
    "Estonia",
    "",
    "",
    "Europe",
    "Northern Europe",
    "",
    "",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/coorest-official/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "CCO2",
    "Not known",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.527",
    "1116",
    "Agri10x",
    "Active",
    "https://www.agri10x.com/",
    "Agriculture & Food",
    "Agriculture & Food",
    "Farming",
    "Farming",
    "",
    "",
    "",
    "1,2",
    "",
    "",
    "",
    ",1,2,",
    "2",
    "a blockchain and AI-enabled platform that connects farmers directly with traders and buyers and lets them sell their produce at competitive prices. It also integrated affiliated services, including quality assessment, warehousing, cold storage, and logistics to deliver a full-stack market linkage solution for Indian farmers",
    "",
    "",
    "",
    "Pune",
    "India",
    "",
    "",
    "Asia",
    "Southern Asia",
    "2018",
    "",
    "",
    "",
    "",
    "https://www.linkedin.com/company/agri10x/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Not known",
    "Ethereum, Polygon",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.548",
    "1101",
    "Reneum (Sindicatum Blockchain Technologies)",
    "Active",
    "http://www.reneum.com",
    "Climate & Environment,Energy",
    "Climate & Environment",
    "Climate & carbon reduction,Energy Certificates",
    "Climate & carbon reduction",
    "Energy Certificates",
    "",
    "",
    "13",
    "7, 13",
    "",
    "",
    ",13,7,13,",
    "3",
    "a climate marketplace about to launch a renewable energy-backed token",
    "",
    "",
    "",
    "Singapore",
    "Singapore",
    "",
    "",
    "Asia",
    "Southeast Asia",
    "2018",
    "",
    "",
    "",
    "",
    "https://www.linkedin.com/company/reneum/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "GREN",
    "Not known",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
  ],
  [
    "",
    "JAFS",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.355",
    "1227",
    "Changeblock",
    "Active",
    "https://www.changeblock.com/",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & carbon reduction",
    "Climate & carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "a platform connecting project developers, climate assets, data and finance in a trustworthy, transparent climate ecosystem.",
    "",
    "",
    "",
    "North Lambeth",
    "United Kingdom",
    "",
    "",
    "Europe",
    "Western Europe",
    "2021",
    "",
    "startup",
    "",
    "",
    "https://www.linkedin.com/company/changeblock/about/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.632",
    "1121",
    "EthaVerse",
    "Active",
    "https://www.ethaverse.io/",
    "Climate & Environment,Finance & Insurance,Energy",
    "Climate & Environment",
    "Waste & recycling,investing & impact investing,Energy Certificates,Climate & carbon reduction",
    "Waste & recycling",
    "investing & impact investing",
    "Energy Certificates",
    "Climate & carbon reduction",
    "12",
    "1, 17",
    "7, 13",
    "13",
    ",12,1,17,7,13,13,",
    "6",
    "a project that leverages the power of staking and bonding pioneered by OlympusDAO and KlimaDAO to fund highly-vetted global renewable energy projects",
    "",
    "",
    "",
    "New York",
    "United States",
    "",
    "",
    "North America",
    "North America",
    "2021",
    "",
    "DAO",
    "https://mobile.twitter.com/EthaVerseDAO/with_replies",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.535",
    "1100",
    "klimaDAO",
    "Active",
    "https://www.klimadao.finance/",
    "Finance & Insurance, Climate & Environment",
    "Climate & Environment",
    "Energy certificates",
    "Energy certificates",
    "investing & impact investing",
    "",
    "",
    "7, 13",
    "1, 17",
    "",
    "",
    ",7,13,1,17,",
    "4",
    "a DAO with aim to acquire as many carbon offsets as it can to drive up their value and make offset-generating activities more profitable",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#N/A",
    "#N/A",
    "2021",
    "",
    "DAO",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "KLIMA",
    "Public",
    "Ethereum, Polygon",
    "https://coinmarketcap.com/currencies/klimadao/",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.507",
    "1114",
    "Toucan Protocol",
    "Active",
    "\nhttps://toucan.earth",
    "Climate & Environment",
    "Climate & Environment",
    "Climate & carbon reduction",
    "Climate & carbon reduction",
    "",
    "",
    "",
    "13",
    "",
    "",
    "",
    ",13,",
    "1",
    "an open and decentralized climate finance ecosystem",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#N/A",
    "#N/A",
    "2021",
    "",
    "DAO",
    "",
    "",
    "https://www.linkedin.com/company/toucan-protocol/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "BCT",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.521",
    "1127",
    "Carbonyzed.xyz",
    "Active",
    "https://www.carbonized.xyz/",
    "Climate & Environment,Digital content & Arts",
    "Climate & Environment",
    "Climate & carbon reduction,Arts Music & Film",
    "Climate & carbon reduction",
    "Arts Music & Film",
    "",
    "",
    "13",
    "16",
    "",
    "",
    ",13,16,",
    "2",
    "an art project that removes tokenized carbon offsets from circulation, pushing the blockchain to go carbon negative as an on-chain carbon sink",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#N/A",
    "#N/A",
    "2021",
    "",
    "",
    "https://twitter.com/CarbonizedNFT",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Polygon",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ECOTA",
    "",
    "",
    "",
    "",
    "",
    "",
    "x",
  ],
  [
    "",
    "JAFS",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.37",
    "1206",
    "Royal",
    "Active",
    "https://royal.io/",
    "Digital content & Arts",
    "Digital content & Arts",
    "Arts Music & Film,Right Management",
    "Arts Music & Film",
    "Right Management",
    "",
    "",
    "16",
    "9, 16",
    "",
    "",
    ",16,9,16,",
    "3",
    "a blockchain technology to enable anyone to own rights in songs.",
    "",
    "",
    "",
    "Austin",
    "United States",
    "",
    "",
    "North America",
    "North America",
    "2021",
    "",
    "Start-up",
    "https://twitter.com/join_royal",
    "",
    "https://www.linkedin.com/company/joinroyal/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ehtereum, Solana, Polygon",
  ],
  [
    "",
    "JAFS",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.358",
    "1197",
    "Bottlepay",
    "Active",
    "https://bottlepay.com/",
    "Finance & Insurance",
    "Finance & Insurance",
    "Peer-to-peer transactions",
    "Peer-to-peer transactions",
    "",
    "",
    "",
    "1, 17",
    "",
    "",
    "",
    ",1,17,",
    "2",
    "an application built on Lightning Network enabling the instantaneous transfer of any amount, making sending and receiving payments a seamless experience.",
    "",
    "",
    "",
    "London",
    "United Kingdom",
    "",
    "",
    "Europe",
    "Western Europe",
    "2019",
    "",
    "Start-up",
    "https://twitter.com/bottlepay?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Bitcoin, Lightning Network",
    "",
    "https://github.com/bottlepay",
  ],
  [
    "",
    "PB contributor (add or edit): : Nhan",
    "Positiveblockchain",
    "",
    "",
    "",
    "Circles is incorporated as a Cooperative (LCA) in Colorado with its sister company, the Basic Income Lab GmbH in Germany. Currently run by 8 contributors.",
    "0.546",
    "58",
    "Circles",
    "Active",
    "https://joincircles.net/",
    "Finance & Insurance",
    "Finance & Insurance",
    "Universal Basic Income,Circular Economy",
    "Universal Basic Income",
    "",
    "",
    "",
    "43,009",
    "",
    "",
    "",
    ",1,10,17,",
    "3",
    "an electronic cryptocurrency with the aim to create and distribute a globally accessible Universal Basic Income.\n",
    "Circles is a proposal for an electronic cryptocurrency with the aim to create, distribute and maintain Universal Basic Income. It is based on individualised currencies and a social graph of trust between these currencies. When new users join Circles, their personal cryptocurrency is created on a smart contract-enabled blockchain. This currency is then regularly minted and added to their account, forming the basis of Circles' UBI properties. The money becomes valuable only if the account owner connects to other accounts, and agrees to trust their personal currencies, treating them as identical to any other Circles currencies that they hold. These trust relationships form circles, fostering local networks and mutual economic cooperation. Through the use of blockchain technology, we expect Circles to be both resilient and globally accessible, which may be the key catalyst to make a Universal Basic Income achievable within the near future.\n" +
      "\n" +
      "Credit-Based\n" +
      "In traditional debt-based currencies one sells goods, borrows money, or invests working power to receive money. With Circles, one receives money unconditionally to engage with their community, creating value through offering goods or services.\n" +
      "\n" +
      "Decentralized\n" +
      "A worldwide basic income is something so powerful that no single entity should have control over the money or its recipients. Using blockchain technology, Circles will be independent of any central issuing authority or institution.\n" +
      "\n" +
      "Resilient\n" +
      "Circles will run on the blockchain, a secure, decentralised, and autonomously managed database. Since the system's money emerges from a network of peer-to-peer relationships, it is possible to maintain stability on a local level, regardless of how things go at the national or global scale.\n" +
      "\n" +
      "Fostering Cooperation\n" +
      "Circles promotes cooperation and economic interaction by creating local trade networks. The more connected community members are to each other, the more valuable their network becomes.\n" +
      "\n" +
      "Hoarding Resistant\n" +
      "Circles has an inbuilt inflation target of 5% per annum to discourage hoarding. This also increases the velocity of money in circulation, creating more opportunities for exchange and economic activity.\n" +
      "\n" +
      "Seigniorage\n" +
      "Seigniorage refers to the profit made from the difference between the production costs and the value of money. As Circles is a credit-based currency that costs almost nothing to create, you will retain almost all of this value as first spender.",
    "",
    "Basic Income on the Blockchain",
    "Berlin",
    "Germany",
    "",
    "",
    "Europe",
    "Central Europe",
    "2015",
    "Ed Murphy; Ronit Kory; Martin Köppelmann; Harriet von Froreich; Anne Walther; Karenina Schröder",
    "start-up",
    "https://twitter.com/CirclesUBI",
    "https://business.facebook.com/CirclesUBI/?ref=py_c",
    "",
    "",
    "https://www.youtube.com/watch?v=wKsQ-kERiH0",
    "https://github.com/CirclesUBI/docs/blob/master/Circles.md",
    "",
    "",
    "https://opencollective.com/circles",
    "",
    "",
    "Public",
    "Ethereum, Gnosis chain",
    "",
    "https://github.com/CirclesUBI",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "",
    "Ronald knows Sarah from the Berlin team, she knows about relaunch and happy to claim",
    "info@joincircles.net\n edzillion@gmail.com",
  ],
  [
    "",
    "PB contributor (add or edit): : Matthieu",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.635",
    "346",
    "Ethic Hub",
    "Active",
    "https://www.ethichub.com/es/",
    "Finance & Insurance,Agriculture & Food",
    "Finance & Insurance",
    "Financial Inclusion,Farming",
    "Financial Inclusion",
    "Farming",
    "",
    "",
    "1, 17",
    "1,2",
    "",
    "",
    ",1,17,1,2,",
    "4",
    "a blockchain-based P2P platform connecting investors with profitable small farming communities around the globe",
    "ethicHub aims, through the use of technology and cryptocurrencies, to help eliminating major barriers to global flow of capital by contacting investors in developed countries (with low yield regarding the excess of liquidity), to solvent borrowers in developing countries (with low liquidity and high interest rates), benefiting both parties by obtaining higher yields and lower interest rates respectively.\n" +
      "Regulatory barriers have so far hindered the development of transnational crowdlending platforms, so we believe a fully decentralized system (DAO) will facilitate global transactions between investors and borrowers.\n" +
      "Thanks to the low cost of system use and thanks to the community of project collectors, which allows reliably validation of identity and moral quality of borrowers, the model allows access to 2.000 million unbanked people to the to financial sector.",
    "",
    "Lending with Impact",
    "Madrid",
    "Spain",
    "",
    "",
    "Europe",
    "Southern Europe",
    "2017",
    "",
    "start-up",
    "https://twitter.com/ethichub",
    "https://www.facebook.com/EthicHubPlatform",
    "",
    "",
    "https://www.youtube.com/watch?v=6wfn4MKU-os",
    "https://www.ethichub.com/#documents",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Gnosis Chain",
    "",
    "",
    "",
    "",
    "",
    "South/Central America",
    "",
    "",
    "Lucas, Matthieu have contacts to team",
    "jori.armbruster@ethichub.com",
  ],
  [
    "",
    "added / claimed website",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.445",
    "890",
    "Gooddollar",
    "Active",
    "https://www.gooddollar.org",
    "Finance & Insurance",
    "Finance & Insurance",
    "Universal Basic Income",
    "Universal Basic Income",
    "",
    "",
    "",
    "43,009",
    "",
    "",
    "",
    ",1,10,17,",
    "3",
    "a 100% not-for-profit project, is nurturing an ecosystem – including academics, NGOs, ethical investors, crypto supporters, and anyone who cares about reducing inequality",
    "GoodDollar is a not-for-profit organization that builds tools and products for distributing universal basic income, specifically by leveraging blockchain and digital asset technologies.\n" +
      "\n" +
      "GoodDollar’s goal is to create financial inclusion and deliver financial literacy on a global scale.",
    "",
    "",
    "Tel Aviv",
    "Israel",
    "",
    "",
    "Middle east",
    "Middle east",
    "2018",
    "Yoni Assia",
    "non-profit",
    "https://twitter.com/gooddollarorg",
    "https://www.facebook.com/gooddollarorg",
    "https://www.linkedin.com/company/gooddollarorg/about/",
    "",
    "https://www.youtube.com/watch?v=HWditTnU134",
    "",
    "",
    "",
    "",
    "https://positiveblockchain.io/wp-content/uploads/2019/10/Untitled-design-2.jpg",
    "",
    "Public",
    "Ethereum, Fuse",
    "",
    "",
    "eToro",
  ],
  [
    "",
    "PB contributor (add or edit): : Felix",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.556",
    "350",
    "TE-FOOD",
    "Active",
    "https://www.tefoodint.com/",
    "Agriculture & Food,Logistics & Traceability",
    "Agriculture & Food",
    "Supply Chain Transparency,Food Transparency",
    "Supply Chain Transparency",
    "Food Transparency",
    "",
    "",
    "45,268",
    "2, 15",
    "",
    "",
    ",8,12,2,15,",
    "4",
    "the only fresh food ecosystem which integrates supply chain companies, consumers, and governments/authorities to improve food safety, eliminate food frauds, and decrease costs of the supply chain companies",
    "TE-FOOD is the only fresh food ecosystem which integrates supply chain companies, consumers, and governments/authorities to improve food safety, eliminate food frauds, and decrease costs of the supply chain companies.\n" +
      " Identification tools are applied to livestock, transports, and fresh food packages to follow the items throughout the whole supply chain. Fresh food products in retail can be traced back to their origins together with food safety related information.",
    "",
    "We are reinventing food supply on the emerging markets",
    "Budapest",
    "Hungary",
    "Albstadt",
    "Germany",
    "Europe",
    "Central Europe",
    "2016",
    "Erik Arokszallasi",
    "start-up",
    "https://twitter.com/TE_FOOD",
    "https://www.facebook.com/tefoodintl/",
    "https://www.linkedin.com/company/te-food/about/",
    "",
    "https://www.youtube.com/watch?v=qot-VCUgpng",
    "https://ico.tefoodint.com/te-food-white-paper.pdf",
    "",
    "",
    "https://icobench.com/ico/te-food",
    "",
    "TFOOD",
    "Public",
    "Ethereum, FoodChain",
    "https://coinmarketcap.com/currencies/te-food/",
    "",
    "",
    "Vietnam",
    "Asia, Europe",
    "",
    "",
    "",
    "Nhan in touch with them? tbc",
    "info@te-food.com",
  ],
  [
    "",
    "?",
    "Ethereum Foundation Next Billion",
    "",
    "?",
    "",
    "",
    "0.381",
    "1068",
    "Acre Africa micro-insurance",
    "Active",
    "https://acreafrica.com/",
    "Finance & Insurance,Agriculture & Food",
    "Finance & Insurance",
    "Insurance,Farming",
    "Insurance",
    "Farming",
    "",
    "",
    "1, 17",
    "1,2",
    "",
    "",
    ",1,17,1,2,",
    "4",
    "an organisation implementing blockchain solutions to a microinsurance product that protects thousands of small-scale farmers in Kenya from extreme weather events. The project is in 2021 part of the Ethereum Next Billion fellowship program and will test and showcase Ethereum’s potential to enable the viability and sustainability of products and services that target the bottom of the wealth pyramid",
    "",
    "",
    "",
    "Nairobi",
    "Kenya",
    "",
    "",
    "Africa",
    "Eastern Africa",
    "2018",
    "",
    "non-profit",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Ethereum, Chainlink",
    "",
    "",
    "",
    "Africa",
    "Africa",
  ],
  [
    "",
    "PB contributor (add or edit): : Matthieu",
    "Positiveblockchain",
    "",
    "",
    "",
    "last quality check Karsten: 12.04.19",
    "0.548",
    "47",
    "Dorium",
    "Active",
    "https://www.dorium.vision",
    "Government & Democracy,Finance & Insurance",
    "Finance & Insurance",
    "Investing & Impact investing,Community Mobilization,Impact Verification,Peer-to-peer transactions",
    "Investing & Impact investing",
    "Community Mobilization",
    "Impact Verification",
    "Peer-to-peer transactions",
    "1, 17",
    "11, 16",
    "1, 17",
    "1, 17",
    ",1,17,11,16,1,17,1,17,",
    "8",
    "a socio economic system where an online-community decides about the financing of sustainable projects and the remuneration of successfully obtained long-term value added in social and economic aspects",
    "Creating wealth in a sustainable way Dorium is a socio economic system where an online-community decides about the financing of sustainable projects and the remuneration of successfully obtained long-term value added in social and economic aspects. Funding is provided through the well-directed emission and coining of a new currency (SoBz) which enables the growth of the socio-economic system from within itself",
    "",
    "7th Continent Discovered",
    "Schaan",
    "Liechtenstein",
    "",
    "Lichtenchtein",
    "Europe",
    "Central Europe",
    "2016",
    "Andreas, Lang, Co-Founder",
    "start-up",
    "https://twitter.com/DoriumCoin",
    "https://www.facebook.com/TeamDorium/",
    "https://www.linkedin.com/company/dorium/about/",
    "",
    "https://www.youtube.com/watch?v=Zggx2jXUUlQ",
    "",
    "",
    "",
    "",
    "",
    "",
    "Not known",
    "Cosmos, BNB Chain",
    "",
    "https://github.com/DORIUMdev/dorium-contracts",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lucas and Karsten know Andreas Lang",
    "team@dorium.world",
  ],
  [
    "",
    "PB contributor (add or edit): : Ronald",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.455",
    "496",
    "Blockchain Charity Foundation",
    "Active",
    "https://www.binance.charity/",
    "Aid & Philanthropy",
    "Aid & Philanthropy",
    "Donation & Charities",
    "Donation & Charities",
    "",
    "",
    "",
    "10",
    "",
    "",
    "",
    ",10,",
    "1",
    "a project to transform philanthropy by developing the world’s first decentralized charity foundation",
    "Blockchain Charity Foundation (BCF) is a not-for-profit organization dedicated to the advancement of blockchain-enabled philanthropy towards achieving global sustainable development. BCF aims to transform philanthropy by developing the world’s first decentralized charity foundation to build a future where blockchain technology can be used to end all forms of poverty and inequality, advance sustainable development and ensure that no one is left behind.\n" +
      "\n" +
      "The three focus areas are: \n" +
      "1. Working with global leaders and industry pioneers to steer the future of charitable and philanthropic blockchain-enabled standards\n" +
      "and regulations.\n" +
      "2. Building Blockchain embedded platform development that advances methods of collection and redistribution of wealth for more direct, scalable, and accessible, promoting deeper and broader participation for giving, receiving, and doing.\n" +
      "3. Creating blockchain-empowered social programs for direct impact on the bottom billion: building community resilience and industrial development with scalable blockchain solutions. \n",
    "",
    "We Make Giving Transparent",
    "",
    "Malta",
    "",
    "",
    "Europe",
    "Southern Europe",
    "2018",
    "Changpeng Zhao (Founder Binance), Helen Hai (BCF Management)",
    "corporate",
    "https://twitter.com/BinanceBCF",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Not Known",
    "Ethereum, BNB",
    "",
    "",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "",
    "Maike had some talks with Lina & Athena (the two executive directors of BCF)",
    "bcf@binance.com",
  ],
  [
    "",
    "PB contributor (add or edit): : Ronald",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.467",
    "505",
    "Wave",
    "Active",
    "http://wavebl.com/",
    "Logistics & Traceability",
    "Logistics & Traceability",
    "Supply Chain Transparency",
    "Supply Chain Transparency",
    "",
    "",
    "",
    "45,268",
    "",
    "",
    "",
    ",8,12,",
    "2",
    "a decentralized network and allows them a direct exchange of documents. WAVE's application manages ownership of documents on the blockchain eliminating disputes, forgeries and unnecessary risks",
    "",
    "",
    "",
    "Delaware",
    "United States",
    "",
    "",
    "North America",
    "North America",
    "2015",
    "Gadi Ruschin, CEO",
    "start-up",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Not known",
    "Wave BL",
    "",
    "",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "",
    "",
    "info@waveBL.com",
    "",
    "Gadi Ruschin",
    "Gadi@waveBL.com",
    "Or Garbash",
  ],
  [
    "",
    "PB contributor (add or edit): : Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.462",
    "409",
    "Vinchain",
    "Active",
    "https://vinchain.io/",
    "Transport & Infrastructure,Logistics & Traceability,Identity & Ownership",
    "Transport & Infrastructure",
    "Digital Identity,Transport & Mobility,Certification & Notarization",
    "Digital Identity",
    "Transport & Mobility",
    "Certification & Notarization",
    "",
    "9, 16",
    "45,239",
    "9",
    "",
    ",9,16,9,11,9,",
    "5",
    "an end to falsified data, financial fraud and safety issues for vehicle data",
    "",
    "",
    "Complete vehicle data all in one marketplace",
    "",
    "United States",
    "",
    "",
    "North America",
    "North America",
    "2017",
    "",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/vinchain-io/about/",
    "",
    "",
    "https://vinchain.io/files/white_paper.pdf",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "VINchain",
    "https://coinmarketcap.com/currencies/vinchain/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "info@vinchain.io",
    "",
    "Alex Miles",
    "Alex.Miles@vinchain.io",
  ],
  [
    "",
    "unknown (probably: PB research)",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.408",
    "163",
    "Safe Haven",
    "Active",
    "https://safehaven.io/",
    "Finance & insurance,Identity & Ownership",
    "Identity & Ownership",
    "Digital Identity,Financial Inclusion",
    "Digital Identity",
    "",
    "",
    "",
    "9, 16",
    "",
    "",
    "",
    ",9,16,",
    "2",
    "",
    "who is developing a solution to help refugees to re-build their lives and with a view to help immigrants port their identities.",
    "",
    "The solution to digital inheritance",
    "Desselgem",
    "Belgium",
    "",
    "",
    "Europe",
    "Western Europe",
    "2017",
    "",
    "start-up",
    "",
    "",
    "",
    "",
    "",
    "https://safehaven.io/files/SafeHaven_WhitePaper.pdf",
    "",
    "",
    "",
    "",
    "",
    "Public",
    "Vechain",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "info@safehaven.io",
    "",
    "Jürgen Schouppe",
  ],
  [
    "",
    "Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.549",
    "1106",
    "FoodGates",
    "Active",
    "https://foodgates.cn/",
    "Agriculture & Food,Logistics & Traceability",
    "Agriculture & Food",
    "Supply Chain Transparency,Food Transparency",
    "Supply Chain Transparency",
    "Food Transparency",
    "",
    "",
    "45,268",
    "2, 15",
    "",
    "",
    ",8,12,2,15,",
    "4",
    "a new generation B2B food platform directly connecting Food & Beverage producers and Chinese buyers. The platform can provide granular insights such as cow selection, slaughtering processes, packaging and cross-continental shipping, all the way to restaurants and customers.",
    "",
    "",
    "",
    "",
    "France",
    "",
    "",
    "Europe",
    "Western Europe",
    "2020",
    "",
    "",
    "",
    "",
    "https://foodgates.cn/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Not known",
    "VeChain",
    "",
    "",
    "",
    "France, China",
    "Europe, Asia",
    "Western Europe, Eastern China",
  ],
  [
    "",
    "PB contributor (add or edit): : Ronald",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.618",
    "313",
    "VeChain foundation",
    "Active",
    "https://www.vechain.org/",
    "Logistics & Traceability,Agriculture & Food",
    "Logistics & Traceability",
    "Supply Chain Transparency,Food Transparency",
    "Supply Chain Transparency",
    "",
    "",
    "",
    "45,268",
    "",
    "",
    "",
    ",8,12,",
    "2",
    "a partnership utilizing the supply chain enhancement capabilities of the VeChain platform for the benefit of BMW’s business process",
    "VeChain is primarily a Blockchain-as-a-Service (BaaS) firm that has a particular focus on the Internet of Things (IoT). The platform uses the power of the blockchain to authenticate and guarantee the quality of goods on a supply chain. The blockchain authentication is achieved using smart chips which monitor and tracks the goods throughout the supply chain, recording securely on the distributed ledger.",
    "",
    "",
    "Singapore",
    "Singapore",
    "",
    "",
    "Asia",
    "Southeast Asia",
    "2015",
    "Sunny Lu, Chief Executive Officer",
    "partnership, corporate, non profit",
    "https://twitter.com/vechainofficial",
    "https://www.facebook.com/groups/VechainThor/",
    "",
    "",
    "https://www.youtube.com/watch?v=vfAEir7uT_g",
    "",
    "",
    "",
    "https://www.vechain.org/",
    "",
    "VET",
    "Public",
    "VeChain",
    "",
    "",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "",
    "",
    "info@vechain.com",
  ],
  [
    "",
    "unknown (probably: PB research)",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.53",
    "431",
    "The Sun Protocol",
    "Inactive",
    "https://TheSunProtocol.io/",
    "Finance & Insurance,Climate & Environment,Energy",
    "Energy",
    "Energy Certificates,Financial Inclusion",
    "Energy Certificates",
    "Financial Inclusion",
    "",
    "",
    "7, 13",
    "1, 17",
    "",
    "",
    ",7,13,1,17,",
    "4",
    "a sustainable & self-determined crypto-economy through energy and benefits. (Project seems inactive or has been aborted)",
    "We are the fusion of sustainability and crypto oriented entrepreneurs. We are Climate Warriors and Blockchainers.\n" +
      "Our Solartainer® can create more than 50.000 kWh of electricity per year. Enough to provide electricity for roughly 4.000 inhabitants. Our energy is sold in local currency and is competitively and fairly priced.\n" +
      "Our SmartMeters measure the usage of the energy according to what the people deem important and the SmartMeters report this to SmartContracts, which then generate our token. The loyalty token guarantees a fixed amount of electricity from the Solartainer®. \n" +
      "We are creating a token representing energy in one network. A token backed by energy. Produced by the sun. We are The Sun Protocol.",
    "",
    "decentralized energy - self-determined prosperity",
    "Hainburg",
    "Germany",
    "",
    "",
    "Europe",
    "Central Europe",
    "2018",
    "Sebnem Rusitschka; Torsten Schreiber; Samater Liban",
    "partnership",
    "https://twitter.com/TheSunProtocol",
    "https://www.facebook.com/thesunprotocol.io/",
    "",
    "",
    "https://www.youtube.com/watch?v=N0HVUFrVGwA&feature=youtu.be",
    "WIP (contact for access)",
    "",
    "",
    "https://medium.com/@thesunprotocol",
    "",
    "",
    "",
    "Tobalaba, Ethereum",
    "",
    "",
    "A research initiative of Freeelio & Africa GreenTec supported by Programming a Sustainable World Initiative at the Cryptoeconomics Institute of WU Vienna",
    "Africa",
    "Africa",
    "",
    "",
    "",
    "Lucas & Nhan know Sam from Darmstadt",
    "Sam@TheSunProtocol.io",
  ],
  [
    "",
    "PB contributor (add or edit): : Lucas",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.433",
    "546",
    "Lutricity",
    "Inactive",
    "http://www.twl.de/de/Unternehmen/Newsroom/Pressemeldungen/Pressearchiv1/Pressemitteilungen/TWL-testet-Blockchain-Technologie-und-simuliert-Energiemarkt-von-morgen.html",
    "Energy",
    "Energy",
    "Energy",
    "Energy",
    "",
    "",
    "",
    "7, 13",
    "",
    "",
    "",
    ",7,13,",
    "2",
    "a partnership with the city of Ludwigshafen in Germany to create a self-sufficient microgrid with distributed producers and consumers, which can control and balance itself via the blockchain. (Project seems inactive or has been aborted)",
    "",
    "",
    "",
    "Ludwigshafen",
    "Germany",
    "",
    "",
    "Europe",
    "Central Europe",
    "2017",
    "",
    "Public-Private-Partnership",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/watch?v=mYuza0ho7Kg",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tobalaba",
    "",
    "",
    "TWL,PwC",
    "Germany",
    "Europe",
    "Western Europe",
    "",
    "",
    "",
    "edifact_lieferant@twl.de_der.cer",
    "",
    "Thomas Mosl",
  ],
  [
    "",
    "pb website form",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.412",
    "1203",
    "RAZ Finance",
    "Active",
    "https://razfinance.io",
    "Finance & Insurance",
    "Finance & Insurance",
    "Impact Verification,investing & impact investing",
    "Impact Verification",
    "investing & impact investing",
    "",
    "",
    "1, 17",
    "1, 17",
    "",
    "",
    ",1,17,1,17,",
    "4",
    "a project which catalyzes decentralized regeneration across an evolving social network for impact finance",
    "RAZ can support projects at any stage\n" +
      "\n" +
      "from grassroots initiatives and growing businesses to municipal green transitions on a city-wide level and beyond.\n" +
      "\n" +
      "Project Owners retain data control and ownership rights related to their version of RAZ, while customizing impact metrics, access and publication settings\n" +
      "\n" +
      "Actions and results are recorded while unfolding, as a digital “time capsule”on the Tezos blockchain \n" +
      "\n" +
      "Awareness-raising and support for our project was initiated by the Ocean DAO through grant funding in August and October 2021, and is being continued by grant and marketing support from the Tezos Foundation, fundraising with Sigma World in Malta, as well as an integration partnership with SupraOracles. \n" +
      "\n" +
      "We are finalizing a city-wide pilot project with the Jerusalem Municipality. http://jerusalemmunicipality.flywheelsites.com \n" +
      "\n" +
      "That will open the door for cities worldwide to utilize RAZ to engage their stakeholders, track funding allocation, verify, measure and manage project impact. \n" +
      "\n" +
      "Our second pilot is with the Daniel Cates Foundation https://razimpactmvp.flywheelsites.com to track data related to childhood education outcomes across the charitable projects the Foundation supports. The pilot will position RAZ as an effective solution for grant-makers and donors to track integrated impact and financial performance. \n" +
      "\n" +
      "Tokenomics - https://razfinance.io/tokenomics \n" +
      "\n" +
      "Starting from February 2022, we are establishing the headquarters of RAZ in Ireland\n" +
      "\n" +
      "This will allow us to align with EU regulations on Anti Money Laundering and Financial Securities Trading ahead of our ICO, which we intend to launch in full regulatory compliance. \n" +
      "\n" +
      "Our platform will issue Decentralized Identifiers to pre-screened individual investors, and therefore provide a secure mechanism for impact investing in cryptocurrency. Through our transparent process, we intend to draw mainstream sustainability, impact and ESG investors towards Decentralized Finance. \n" +
      "\n" +
      "Our multi-stakeholder approach will allow us to bring together funders \n" +
      "\n" +
      "including municipalities, organizations, investment funds, individual investors\n" +
      "\n" +
      "and \n" +
      "\n" +
      "Verified, transparent, projects, initiatives, businesses and charities realizing genuine positive impact for our planet and its people \n" +
      "\n" +
      "Team - https://razfinance.io/team \n" +
      "\n" +
      "Our Co-Founders have been brought together by shared values and a commitment to making the world a better place through impact finance. Throughout our research and development phase, our company became a Certified B Corporation and In 2021, we were recognized as a “Best for the World” B Corporation in the Workers’ Impact category. RAZ Finance was further nominated in the top 5 global environment, social and governance projects in the blockchain space by the Crypto AM Awards in London. \n" +
      "\n" +
      "We have established a partnership with a skilled design and development team in order to build our Tezos and Ethereum-integrated MVP. \n" +
      "\n" +
      "Our advisors’ experience spans across blockchain, finance, impact data management and verification, as well as significant sustainability-driven projects across the world.  ",
    "",
    "",
    "Dublin",
    "Ireland",
    "",
    "",
    "Europe",
    "Western Europe",
    "2021",
    "",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/razfintech/",
    "",
    "https://www.youtube.com/watch?v=ol0nIvxy9gY",
    "",
    "",
    "",
    "",
    "",
    "RAZ",
    "Public",
    "Tezos, Cardano, Ethereum",
    "",
    "",
    "",
    "Global",
    "Global",
    "Global",
  ],
  [
    "",
    "PB contributor (add or edit): : Khalid",
    "Positiveblockchain",
    "",
    "JA (BFG)",
    "44501",
    "JAFS, data verified with Gravity November 2021",
    "0.504",
    "752",
    "Gravity",
    "Active",
    "https://www.gravity.earth/",
    "Identity & Ownership,Finance & Insurance,Aid & Philanthropy",
    "Identity & Ownership",
    "Digital Identity,Development & Aid,Lending",
    "Digital Identity",
    "Development & Aid",
    "Lending",
    "",
    "9, 16",
    "10",
    "1, 17",
    "",
    ",9,16,10,1,17,",
    "5",
    "a digital identity solutions which empower individuals, international organisations and governments to build trusted digital identities that are private, portable and persistent.",
    "Gravity’s digital identity solutions empower individuals, international organisations and governments to build trusted digital identities that are private, portable and persistent.\n" +
      "With Gravity:\n" +
      "● Organisations can efficiently collect verifiable data for improved service delivery, interoperability, data privacy and impact.\n" +
      "● Users can safely share their personal data to access humanitarian aid, financing, employment opportunities, educational resources and government services to accelerate their path towards financial inclusion.",
    "",
    "digital identities to accelerate the financial inclusion and empowerment of all people",
    "Nairobi",
    "Kenya",
    "Paris",
    "France",
    "Africa",
    "Eastern Africa",
    "2017",
    "Johannes Ebert",
    "start-up",
    "https://twitter.com/gravityID_earth",
    "",
    "https://www.linkedin.com/company/gravity-earth/about/",
    "",
    "",
    "",
    "",
    "",
    "https://docs.gravity.earth/",
    "",
    "",
    "Public",
    "Tezos",
    "",
    "",
    "",
    "Africa",
    "Africa",
    "",
    "",
    "",
    "",
    "contact@gravity.earth",
    "",
    "Johannes Ebert",
  ],
  [
    "",
    "JAFS",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.383",
    "1067",
    "Electis",
    "Active",
    "https://www.electis.app/static/landing/index.4a6e835292bc.html",
    "Government & Democracy",
    "Government & Democracy",
    "Voting",
    "Voting",
    "",
    "",
    "",
    "9, 16",
    "",
    "",
    "",
    ",9,16,",
    "2",
    "Safe voting title-checkmark for grassroots communities",
    "",
    "",
    "",
    "Paris",
    "France",
    "",
    "",
    "Europe",
    "Western Europe",
    "2018",
    "",
    "non profit",
    "https://twitter.com/ElectisNGO",
    "",
    "https://www.linkedin.com/company/electisngo/about/",
    "",
    "",
    "",
    "",
    "",
    "https://www.electis.io/",
    "",
    "",
    "Public",
    "TEZOS",
    "",
    "",
    "",
    "Global",
    "Global",
    "Global",
  ],
  [
    "",
    "JAFS",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.373",
    "1226",
    "Klapcoin",
    "Active",
    "https://klapcoin.fr/",
    "Digital content & Arts,Finance & Insurance\t",
    "Digital content & Arts",
    "Arts Music & Film,Crowdfunding",
    "Arts Music & Film",
    "Crowdfunding",
    "",
    "",
    "16",
    "1, 17",
    "",
    "",
    ",16,1,17,",
    "3",
    "a decentralized funding applciation for french cinma industry",
    "",
    "",
    "",
    "Paris",
    "France",
    "",
    "",
    "Europe",
    "Western Europe",
    "2022",
    "",
    "startup",
    "https://twitter.com/klapcoin",
    "",
    "https://www.linkedin.com/company/la-dcf/about/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "LUX",
    "Public",
    "Tezos",
  ],
  [
    "",
    "unknown (probably: PB research)",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.436",
    "175",
    "Ponton Enerchain",
    "Inactive",
    "https://enerchain.ponton.de/",
    "Energy,Finance & Insurance",
    "Energy",
    "Energy,Peer-to-peer transactions",
    "Energy",
    "Peer-to-peer transactions",
    "",
    "",
    "7, 13",
    "1, 17",
    "",
    "",
    ",7,13,1,17,",
    "4",
    "the first distributed platform marketplace for OTC trading of wholesale energy products",
    "Ponton is a German innovative software company, develops platforms and B2B solutions, especially for EFET. Developped Enerchain, the first distributed platform marketplace for OTC trading of wholesale energy products = a consortium of European energy trading companies testing blockchain for P2P trading",
    "",
    "",
    "Hamburg",
    "Germany",
    "",
    "",
    "Europe",
    "Central Europe",
    "2018",
    "Dr. Michael Merz, Managing Partner; Tilo Zimmermann, Managing Partner",
    "start-up,partnership",
    "https://twitter.com/enerchain",
    "https://www.facebook.com/EnLedger/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tendermint",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "lucas knows CEO",
    "info@enerchain.ponton.de",
  ],
  [
    "",
    "JAFS",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.375",
    "1083",
    "Unbiased",
    "Active",
    "https://unbiased.cc/",
    "Digital content & Arts",
    "Digital content & Arts",
    "Blockchain Social Media",
    "Blockchain Social Media",
    "",
    "",
    "",
    "9, 16",
    "",
    "",
    "",
    ",9,16,",
    "2",
    "Data Marketplace platform (In Beta), a one-stop-shop B2B solution helping enterprises working with AI and Machine Learning applications, by providing privacy-preserved and decentralized AI development tools",
    "",
    "",
    "",
    "Göteborg",
    "Sweden",
    "",
    "",
    "Europe",
    "Northern Europe",
    "2018",
    "",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/unbiased/about/",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Not known",
    "Telos",
    "",
    "",
    "",
    "Distributed",
    "Distributed",
    "Distributed",
  ],
  [
    "",
    "Pierre Champsavoir",
    "Blockchain for Good",
    "",
    "",
    "",
    "",
    "0.383",
    "996",
    "Korapay",
    "Active",
    "https://www.korapay.com/",
    "Finance & Insurance",
    "Finance & Insurance",
    "Peer-to-peer transactions",
    "Peer-to-peer transactions",
    "",
    "",
    "",
    "1, 17",
    "",
    "",
    "",
    ",1,17,",
    "2",
    "a cross-border payment solution to lower the cost of remittance of individual and business payments into and within Africa",
    "",
    "",
    "",
    "Toronto",
    "Canada",
    "",
    "",
    "North America",
    "North America",
    "2018",
    "",
    "start-up",
    "",
    "",
    "https://www.linkedin.com/company/kora-pay/about/",
    "",
    "",
    "",
    "",
    "",
    "support@korapay.com",
    "",
    "",
    "",
    "TBC",
    "",
    "",
    "Techstar",
    "Nigeria",
    "Africa",
  ],
  [
    "",
    "added / claimed website",
    "Positiveblockchain",
    "",
    "",
    "",
    "",
    "0.512",
    "487",
    "Woolf",
    "Inactive",
    "https://woolf.university",
    "Education & Employment",
    "Education & Employment",
    "Education",
    "Education",
    "",
    "",
    "",
    "4",
    "",
    "",
    "",
    ",4,",
    "1",
    "the first borderless, blockchain-powered university in the world",
    "Woolf will be the first fully accredited, borderless, blockchain-powered university. Woolf will use blockchain technology to enforce regulatory compliance, eliminate or automate bureaucratic university processes, and manage the custodianship of sensitive financial and personal data. As the first university built entirely on a blockchain architecture, Woolf promises to disrupt the economics of higher education by providing new opportunities for both students and academics. Woolf is currently developing an accredited platform on which students and teachers can connect, anywhere in the world. Woolf focusses on Oxbridge-style tutorials that prioritise personal interactions between teachers and students. Although the Woolf software platform is online, it will support both in-person and distance teaching. Woolf has appeared in news outlets globally in ten languages, including Forbes, Nasdaq, The Times, CoinTelegraph, and Bitcoinnews.\n" +
      "See our FAQs: https://woolf.university/#/FAQs",
    "",
    "Woolf will be the first borderless, blockchain-powered university",
    "Oxford",
    "United Kingdom",
    "Berlin",
    "Germany",
    "Europe",
    "Western Europe",
    "2018",
    "Dr Joshua Broggi",
    "academic",
    "http://bit.ly/WoolfTwitter",
    "http://bit.ly/WoolfFacebook",
    "",
    "",
    "https://www.youtube.com/watch?v=AfoDzY_CHp8",
    "https://woolf.university/assets/doc/whitepaper.pdf",
    "",
    "",
    "Telegram community: http://bit.ly/WoolfTelegram ; \n" +
      "Blog: https://medium.com/the-woolf-company-blog\n",
    "",
    "",
    "",
    "Stellar, Hyperledger",
    "",
    "",
    "",
    "Global",
    "Global",
    "Global",
    "",
    "",
    "",
    "communications@woolf.university\n jonathan.duquette@woolf.university",
  ],
];
